services:
  gps-tracker-service:
    container_name: gps-track-service
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    ports:
      - "8080:4000"
    environment:
      - DB_URL=postgresql://postgres:password@db:5432/gpstrack
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal

  db:
    build:
      dockerfile: Dockerfile.postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gpstrack
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_cron"
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d gpstrack'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

networks:
  internal:
