services:
  gps-tracker-service:
    container_name: gps-track-service
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    ports:
      - "8080:4000"
    environment:
      - DB_URL=${DB_URL}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal

  test-runner:
    container_name: gps-tests-runner
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: test_runner
    env_file:
      - ../.env
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      db:
        condition: service_healthy
      gps-tracker-service:
        condition: service_started
    networks:
      - internal

  db:
    container_name: gps-db
    build:
      dockerfile: Dockerfile.postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gpstrack
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_cron"
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gpstrack"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

networks:
  internal:
